# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_ego'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ego',
        ),
    ]
