# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171130_1418'),
    ]

    operations = [
    ]
