# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
